name: heads_web3
channels:
- defaults
- main
dependencies:
- astropy=2.0.2
- click=6.7
- coverage=4.4.2
- flask=0.12.2
- hypothesis=3.38.5
- intel-openmp=2018.0.0
- itsdangerous=0.24
- jinja2=2.10
- libffi=3.2.1
- libgfortran=3.0.0
- markupsafe=1.0
- mkl=2017.0.3
- ncurses=5.9
- numpy=1.13.1
- openssl=1.0.2l
- pip=9.0.1
- py=1.4.34
- pytest=3.2.1
- python=3.6.2
- readline=6.2
- setuptools=36.4.0
- six=1.9.0
- sqlite=3.13.0
- tk=8.5.18
- werkzeug=0.12.2
- wheel=0.29.0
- xz=5.2.3
- zlib=1.2.11
- zope=1.0
- zope.interface=4.4.2
- pip:
  - dominate==2.3.1
  - flask-bootstrap==3.3.7.1
  - visitor==0.1.3

