name: heads_web3
channels:
- defaults
- main
dependencies:
- astropy=2.0.2
- attrs=17.3.0
- ca-certificates=2017.08.26
- certifi=2017.11.5
- click=6.7
- coverage=4.4.2
- flask=0.12.2
- hypothesis=3.38.5
- intel-openmp=2018.0.0
- itsdangerous=0.24
- jinja2=2.10
- libcxx=4.0.1
- libcxxabi=4.0.1
- libedit=3.1
- libffi=3.2.1
- libgfortran=3.0.1
- markupsafe=1.0
- mkl=2018.0.1
- ncurses=6.0
- numpy=1.14.0
- openssl=1.0.2n
- pip=9.0.1
- pluggy=0.6.0
- py=1.5.2
- pympler=0.5
- pytest=3.3.0
- python=3.6.4
- readline=7.0
- setuptools=36.5.0
- six=1.11.0
- sqlite=3.20.1
- tk=8.6.7
- werkzeug=0.12.2
- wheel=0.30.0
- xz=5.2.3
- zlib=1.2.11
- zope=1.0
- zope.interface=4.4.3
- pip:
  - dominate==2.3.1
  - flask-bootstrap==3.3.7.1
  - visitor==0.1.3

